/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDietaRouteImport } from './routes/_authenticated/dieta'
import { Route as AuthenticatedEstrategiaRouteImport } from './routes/_authenticated/estrategia'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedListaComprasRouteImport } from './routes/_authenticated/lista-compras'
import { Route as AuthenticatedMeuDiaRouteImport } from './routes/_authenticated/meu-dia'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTreinoRouteImport } from './routes/_authenticated/treino'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietaRoute = AuthenticatedDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstrategiaRoute = AuthenticatedEstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListaComprasRoute =
  AuthenticatedListaComprasRouteImport.update({
    id: '/lista-compras',
    path: '/lista-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuDiaRoute = AuthenticatedMeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinoRoute = AuthenticatedTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/estrategia': typeof AuthenticatedEstrategiaRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/estrategia': typeof AuthenticatedEstrategiaRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dieta': typeof AuthenticatedDietaRoute
  '/_authenticated/estrategia': typeof AuthenticatedEstrategiaRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/lista-compras': typeof AuthenticatedListaComprasRoute
  '/_authenticated/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/treino': typeof AuthenticatedTreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/checkin'
    | '/dashboard'
    | '/dieta'
    | '/estrategia'
    | '/evolucao'
    | '/lista-compras'
    | '/meu-dia'
    | '/onboarding'
    | '/perfil'
    | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/checkin'
    | '/dashboard'
    | '/dieta'
    | '/estrategia'
    | '/evolucao'
    | '/lista-compras'
    | '/meu-dia'
    | '/onboarding'
    | '/perfil'
    | '/treino'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dieta'
    | '/_authenticated/estrategia'
    | '/_authenticated/evolucao'
    | '/_authenticated/lista-compras'
    | '/_authenticated/meu-dia'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dieta': {
      id: '/_authenticated/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AuthenticatedDietaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategia': {
      id: '/_authenticated/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof AuthenticatedEstrategiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista-compras': {
      id: '/_authenticated/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof AuthenticatedListaComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-dia': {
      id: '/_authenticated/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof AuthenticatedMeuDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino': {
      id: '/_authenticated/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AuthenticatedTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDietaRoute: typeof AuthenticatedDietaRoute
  AuthenticatedEstrategiaRoute: typeof AuthenticatedEstrategiaRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedListaComprasRoute: typeof AuthenticatedListaComprasRoute
  AuthenticatedMeuDiaRoute: typeof AuthenticatedMeuDiaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTreinoRoute: typeof AuthenticatedTreinoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDietaRoute: AuthenticatedDietaRoute,
  AuthenticatedEstrategiaRoute: AuthenticatedEstrategiaRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedListaComprasRoute: AuthenticatedListaComprasRoute,
  AuthenticatedMeuDiaRoute: AuthenticatedMeuDiaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTreinoRoute: AuthenticatedTreinoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
