-- Mídia dos exercícios (ExerciseDB) — grava media_url. Idempotente.
-- Vídeos MP4 animados, servidos por cdn.exercisedb.dev (CDN público).
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/N75Uemp/41n2hxnFMotsXTj3__Barbell-Bench-Press_Chest2_.mp4' WHERE name='Supino reto com barra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/s8X7w7I/41n2hsVHu7B1MTdr__Dumbbell-Palms-In-Incline-Bench-Press.mp4' WHERE name='Supino inclinado com halteres';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/G8ZH9KB/41n2hNXJadYcfjnd__Push-up-m_Chest.mp4' WHERE name='Flexão de braço';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nQSzfrK/41n2hXXpvbykPY3q__Incline-Push-up_Chest.mp4' WHERE name='Flexão inclinada';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/Pz2nxBg/41n2hftBVLiXgtRQ__Wide-Grip-Pull-Up_Back.mp4' WHERE name='Puxada frontal';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/zjTR7xI/41n2hHdjQpnyNdie__Dumbbell-Bent-over-Row_Back_.mp4' WHERE name='Remada curvada com barra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/7imWBgZ/41n2hY9EdwkdGz9a__Dumbbell-Bent-over-Row_Back_.mp4' WHERE name='Remada unilateral com halter';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/AYBx4nr/41n2hsBtDXapcADg__Pull-up_Back_.mp4' WHERE name='Barra fixa';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/im3VsRd/41n2hdkBpqwoDmVq__Suspended-Row_Back_.mp4' WHERE name='Remada com elástico';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/2aScjba/41n2hfYD2sH4TRCH__Hyperextension_Waist.mp4' WHERE name='Superman';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/OCSQUGO/41n2hmGR8WuVfe1U__Bodyweight-Squat-(male)_Thighs-SIDE-POV_.mp4' WHERE name='Agachamento livre';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nFmXQAf/41n2hQDiSwTZXM4F__Dumbbell-Goblet-Squat_Thighs.mp4' WHERE name='Leg press';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nFu4fli/41n2hw8nSYiaCXW1__Sissy-Squat-Bodyweight_Thighs_.mp4' WHERE name='Cadeira extensora';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/OCSQUGO/41n2hmGR8WuVfe1U__Bodyweight-Squat-(male)_Thighs-SIDE-POV_.mp4' WHERE name='Agachamento no peso do corpo';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/cmc5ZI6/41n2hYXWwoxiUk57__Lunge-(female)_Hips.mp4' WHERE name='Afundo';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/bn2Y6tf/41n2hpLLs1uU5atr__Bulgarian-Split-Squat_Thighs.mp4' WHERE name='Agachamento búlgaro';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/sZiAup2/41n2hn8rpbYihzEW__Dumbbell-Romanian-Deadlift_Hips.mp4' WHERE name='Stiff com barra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/GCbG7KH/41n2hQp1pR7heQq9__Dumbbell-Stiff-Leg-Deadlift-(female)_Waist.mp4' WHERE name='Stiff com halteres';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/sZiAup2/41n2hn8rpbYihzEW__Dumbbell-Romanian-Deadlift_Hips.mp4' WHERE name='Good morning';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/HaateGp/41n2hxxePSdr5oN1__Hip-Thrusts_Hips_.mp4' WHERE name='Elevação pélvica';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/HaateGp/41n2hxxePSdr5oN1__Hip-Thrusts_Hips_.mp4' WHERE name='Ponte de glúteo unilateral';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/x17ZdXN/41n2hYAP9oGEZk2P__Sumo-Squat-(male)_Thighs.mp4' WHERE name='Agachamento sumô';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/fe5R356/41n2hs6camM22yBG__Dumbbell-Seated-Shoulder-Press_Shoulders_.mp4' WHERE name='Desenvolvimento com halteres';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/08ys3e3/41n2hMRXm49mM62z__Dumbbell-Arnold-Press-II_Shoulders.mp4' WHERE name='Desenvolvimento militar com barra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/j3qqj9g/41n2hjuGpcex14w7__Dumbbell-Lateral-Raise_shoulder_.mp4' WHERE name='Elevação lateral';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/34FGFWa/41n2hS5UrMusVCEE__Lateral-Raise-with-Towel_Shoulders_.mp4' WHERE name='Elevação lateral com elástico';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/db52igZ/41n2hmvGdVRvvnNY__Pike-Push-up-(on-Bench)-(VERSION-2)_Chest.mp4' WHERE name='Pike push-up';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nuYT8c2/41n2hGioS8HumEF7__Cable-Hammer-Curl-(with-rope)-(male)_Forearms_.mp4' WHERE name='Rosca direta com barra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/a0XElzR/41n2hgCHNgtVLHna__Dumbbell-Cross-Body-Hammer-Curl_Forearms.mp4' WHERE name='Rosca alternada com halteres';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nuYT8c2/41n2hGioS8HumEF7__Cable-Hammer-Curl-(with-rope)-(male)_Forearms_.mp4' WHERE name='Rosca martelo';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/Z80fRjW/41n2hc2VrB8ofxrW__Lying-Double-Legs-Biceps-Curl-with-Towel_Upper-Arms.mp4' WHERE name='Rosca com elástico';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/Efw1JG7/41n2hLA8xydD4dzE__Triceps-Press-(Head-Below-Bench)_Upper-Arms.mp4' WHERE name='Tríceps na polia';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/9UKW2aC/41n2hdHtZrMPkcqY__Dumbbell-Lying-Floor-Skullcrusher_Upper-Arms.mp4' WHERE name='Tríceps testa';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/Efw1JG7/41n2hLA8xydD4dzE__Triceps-Press-(Head-Below-Bench)_Upper-Arms.mp4' WHERE name='Tríceps francês com halter';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/gGHzijt/41n2hadQgEEX8wDN__Triceps-Dip_Upper-Arms_.mp4' WHERE name='Mergulho no banco';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/OltRdJo/41n2hRZ6fgsLyd77__Diamond-Push-up_Upper-Arms.mp4' WHERE name='Flexão diamante';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/u90JU7l/41n2hskeb9dXgBoC__Crunch-Floor-(male)_waist.mp4' WHERE name='Abdominal supra';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nJZVWqt/41n2hXQw5yAbbXL8__Front-Plank-(female)_Waist_.mp4' WHERE name='Prancha';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/xm1Zyp9/41n2hq3Wm6ANkgUz__Lying-Leg-Raise-and-Hold_Hips.mp4' WHERE name='Elevação de pernas';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/nJZVWqt/41n2hXQw5yAbbXL8__Front-Plank-(female)_Waist_.mp4' WHERE name='Prancha lateral';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/u90JU7l/41n2hskeb9dXgBoC__Crunch-Floor-(male)_waist.mp4' WHERE name='Abdominal na máquina';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/4n278Va/41n2hdWu3oaCGdWT__Dumbbell-Standing-Calf-Raise_Calves.mp4' WHERE name='Panturrilha em pé';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/0phu5Sm/41n2hTs4q3ihihZs__Barbell-Seated-Calf-Raise_Calves.mp4' WHERE name='Panturrilha sentado';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/rYfe7Ll/41n2hSGs9Q3NVGhs__Bodyweight-Standing-Calf-Raise_Calves.mp4' WHERE name='Panturrilha no degrau';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/tn5DeIa/41n2hjkBReJMbDJk__Run-on-Treadmill-(female)_Cardio.mp4' WHERE name='Corrida';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/Pq3UCOi/41n2hN468sP27Sac__Jump-Rope-(female)_Cardio_.mp4' WHERE name='Pular corda';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/liwOehn/41n2hupxPcdnktBC__Jumping-Jack-(female)_Cardio.mp4' WHERE name='Polichinelo';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/hcssLQq/41n2hqYdxG87hXz1__Burpee_Cardio_.mp4' WHERE name='Burpee';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/y9OQ8m1/41n2hXYRxFHnQAD4__Stationary-Bike-Run-(version-4)_Cardio.mp4' WHERE name='Bike ergométrica';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/P973giu/41n2hkK8hGAcSnW7__Chest-Dip_Chest.mp4' WHERE name='Crucifixo na máquina';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/xdO6Mmu/41n2hrHSqBnVWRRB__Bodyweight-Single-Leg-Deadlift_Thighs.mp4' WHERE name='Mesa flexora';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/4uTBU4U/41n2hNjcmNgtPJ1H__Bodyweight-Rear-Lunge_Thighs.mp4' WHERE name='Coice na máquina';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/ufB3wo9/41n2haAabPyN5t8y__Side-Lunge_Thighs.mp4' WHERE name='Abdução na máquina';
UPDATE public.exercises SET media_url='https://cdn.exercisedb.dev/w/videos/xdO6Mmu/41n2hrHSqBnVWRRB__Bodyweight-Single-Leg-Deadlift_Thighs.mp4' WHERE name='Flexão nórdica';
